logging:
  project_id: ~
  output_dir: ./outputs
  tensorboard: true
  image: true
  stdout: true
  model_save_options:
    save_optimizer_state: false
    save_best_only: false
    best_model_criterion: loss # metric
    sample_input_size: [640, 640] # Used for flops and onnx exp`ort
    onnx_export_opset: 16 # Recommend in range [13, 17]
    validation_epoch: &validation_epoch 10
    save_checkpoint_epoch: *validation_epoch  # Multiplier of `validation_epoch`.
  metrics:
    classwise_analysis: True
    metric_names: ~ # None for default settings